menu:
- {name: 'home', url: '/'}
- {name: 'sponsors', url: '/sponsors'}
- {name: 'results', url: '/results'}
- {name: 'photos', url: '/photos'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'instagram', link: 'https://instagram.com/johnkeller101'}
- {icon: 'strava', link: 'https://www.strava.com/athletes/johnkeller'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/johnkeller101'}
- {icon: 'github', link: 'https://github.com/johnkeller101'}